#
# Configuration file only for development
#

spring:
  profiles:
    active: ${MOBILE_ACTIVE_PROFILE:live, mysql}

# Logging
logging:
  level:
    com.backbase: INFO
    org.springframework: INFO
    # Temporary: Ignore Eureka Client error messages (workaround) - https://stash.backbase.com/projects/INFRA/repos/api-registry-client/browse
    com.netflix.discovery: OFF


---
### Live profile
spring:
  profiles: live

# Gateway (enable security; configure SSO, Internal JWT, read shared secret from environment key SIG_SECRET_KEY)
backbase:
  web:
    security:
      enabled: true
  mobile:
    ios:
      isProduction: false
      topic: "com.backbase.poc.pushnotifications"
    android:
      url: "https://fcm.googleapis.com/fcm/send"
      key: "License key should be here"
---
###Mysql profile
spring:
  profiles: mysql
  datasource:
    platform: mysql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://:3306/mobile_e?useSSL=false
    username: root
    password: root

