#
# Configuration file only for development
#

contentservices:
  filesystem:
    importLocation: ${BACKBASE_HOME}/contentservices/import
    exportLocation: ${BACKBASE_HOME}/contentservices/export
    fileLocation: ${BACKBASE_HOME}/contentservices/file
  cmis:
    repository:
      content:
        fileLocation: ${BACKBASE_HOME}/contentservices/content

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cs_e?useSSL=false
    username: root
    password: root
