#
# Configuration file only for development
#

provisioning:
  database:
    host: localhost
  appname: provisioning

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/provisioning_e?useSSL=false
    username: root
    password: root
